### ISSUE TITLE
Bug After Update

### ISSUE THREAD

**Issue by faoztas** [ergenekonyigit/trendcat#2]
There is a bug that appears in the bugpic after the update.
![bugpic](https://user-images.githubusercontent.com/18630347/60666321-74399500-9e6f-11e9-8218-a4bffe64d065.PNG)

**Comment by ergenekonyigit** [comment]
Yes, i fix it this bug and publish to chrome store. Probably update will come to tonight.

**Comment by faoztas** [comment]
Yeah, problem is solved. Thanks.
