### ISSUE TITLE
400 Bad request on malformed url

### ISSUE THREAD

**Issue by pupubird** [ergenekonyigit/trendcat#3]
**Describe the bug**
Hey hey, the host for `https://hackertab.pupubird.com` here. 

The request to `https://hackertab.pupubird.com/repositories?language=null&since=daily` is `400`.
The correct format for null language input is `https://hackertab.pupubird.com/repositories?language=&since=daily` 

**Screenshots**
![Screenshot from 2020-11-21 22-49-32](https://user-images.githubusercontent.com/35325976/99880077-1b2cf580-2c4c-11eb-8dfc-b75a1bd3290c.png)

**Comment by ergenekonyigit** [comment]
Thank you for reporting 🙏  I will fix this bug asap.
